У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [8]:
import pandas as pd

df = pd.read_csv('tips.csv')

display(df.head())
display(df.shape)
display(df.columns)
display(df.info())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

(244, 7)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

None

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [9]:
df.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [10]:
df[['total_bill', 'tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [11]:
df.head(10)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [13]:
print(df.loc[5])

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [28]:
bill_over_20 = df[df['total_bill'] > 20]
bill_over_20_sorted = bill_over_20.sort_values(by='total_bill', ascending=False)
print(f"Кількість рахунків більше 20: {len(bill_over_20)}")
print(bill_over_20_sorted.head())

Кількість рахунків більше 20: 97
     total_bill    tip   sex smoker  day    time  size
170       50.81  10.00  Male    Yes  Sat  Dinner     3
212       48.33   9.00  Male     No  Sat  Dinner     4
59        48.27   6.73  Male     No  Sat  Dinner     4
156       48.17   5.00  Male     No  Sun  Dinner     6
182       45.35   3.50  Male    Yes  Sun  Dinner     3

In [30]:
female_customers = df[df['sex'] == 'Female']
print(f"Кількість відвідувачок: {len(female_customers)}")
print(female_customers.head())

Кількість відвідувачок: 87
    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

In [32]:
dinner_bill = df[df['time'] == 'Dinner']
print(f"Кількість рахунків за вечерю; {len(dinner_bill)}")
print(dinner_bill.head())

Кількість рахунків за вечерю; 176
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [36]:
dinner_bill_over_30 = df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)]
print(f"Кількість рахунків за вечерю більше 30: {len(dinner_bill_over_30)}")
print(dinner_bill_over_30.head())

Кількість рахунків за вечерю більше 30: 27
    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [43]:
mean_bill = df['total_bill'].mean()

max_tip = df['tip'].max()

missing_values = df.isnull().sum()

time_counts = df['time'].value_counts()

print(f"1. Середній розмір рахунку: {mean_bill.round(2)}")
print(f"2. Максимальні чайові: {max_tip}")
print(f"3. Пропущені значення по колонках:")
print(missing_values)
print(f"4. Кількість вечерь та обідів:")
print(time_counts)

1. Середній розмір рахунку: 19.79
2. Максимальні чайові: 10.0
3. Пропущені значення по колонках:
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64
4. Кількість вечерь та обідів:
time
Dinner    176
Lunch      68
Name: count, dtype: int64

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [46]:
bysex = df.groupby('sex')['total_bill'].mean().round()
bysex

sex
Female    18.0
Male      21.0
Name: total_bill, dtype: float64

In [50]:
byday = df.groupby('day')['tip'].mean().round(2)
byday

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64

In [51]:
people_per_day = df.groupby('day')['size'].sum()
people_per_day

day
Fri      40
Sat     219
Sun     216
Thur    152
Name: size, dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [53]:
df['tip_percentage'] = (df['tip'] / df['total_bill']) * 100
print(df.head(10))

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
5       25.29  4.71    Male     No  Sun  Dinner     4       18.623962
6        8.77  2.00    Male     No  Sun  Dinner     2       22.805017
7       26.88  3.12    Male     No  Sun  Dinner     4       11.607143
8       15.04  1.96    Male     No  Sun  Dinner     2       13.031915
9       14.78  3.23    Male     No  Sun  Dinner     2       21.853857

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [ ]:
sorted_by_bill = df.sort_values(by='total_bill', ascending=True)

# 3. Топ-5 найбільших чайових (nlargest)
# Перший аргумент - кількість (5), другий - колонка ('tip')
top_5_tips = df.nlargest(5, 'tip')

# --- Виведення результатів ---
print("1. За розміром рахунку (зростання):")
print(sorted_by_bill.head())

print("\n2. За чайовими (спадання):")
print(sorted_by_tip.head())

print("\n3. Топ-5 найбільших чайових (nlargest):")
print(top_5_tips)

In [ ]:
sorted_by_tip = df.sort_values(by='tip', ascending=False)